slTradeIn/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using slTradeIn.DataAccess;
using slTradeIn.Help;
using slTradeIn.Models;

namespace slTradeIn.Controllers;

public class AdminController : CustomController
{
    private readonly Detail_TTU_emailTemplate_Data detail_TTU_EmailTemplate_Data;

    public AdminController(Detail_TTU_emailTemplate_Data detail_TTU_EmailTemplate_Data)
    {
        this.detail_TTU_EmailTemplate_Data = detail_TTU_EmailTemplate_Data;
    }

    // GET: Admin
    public ActionResult EmailTemplate()
    {
        return View(detail_TTU_EmailTemplate_Data.GetAll());
    }

    // GET: Admin/Create
    public ActionResult CreateEmailTemplate()
    {
        return View();
    }

    [HttpPost]
    public ActionResult CreateEmailTemplate(EmailTemplateModel collection)
    {
        if (ModelState.IsValid)
        {
            var etm = new EmailTemplateModel();
            etm.vTemplateName = collection.vTemplateName;
            etm.vSubject = collection.vSubject;
            etm.vHTMLBody = collection.vHTMLBody;
            etm.bActive = true;

            detail_TTU_EmailTemplate_Data.SaveEmailTemplate(etm);

            return RedirectToAction("EmailTemplate");
        }

        return View();
    }


    public ActionResult EditEmailTemplate(int id)
    {
        return View(detail_TTU_EmailTemplate_Data.GetWithId(id));
    }

    [HttpPost]
    public ActionResult EditEmailTemplate(EmailTemplateModel collection)
    {
        if (ModelState.IsValid)
        {
            var etm = new EmailTemplateModel();
            etm.iEmailTemplateID = collection.iEmailTemplateID;
            etm.vTemplateName = collection.vTemplateName;
            etm.vSubject = collection.vSubject;
            etm.vHTMLBody = collection.vHTMLBody;
            etm.bActive = true;
            etm.dUpdatedDate = DateTime.Now;

            detail_TTU_EmailTemplate_Data.UpdateEmailTemplate(etm);

            return RedirectToAction("EmailTemplate");
        }

        return View();
    }

    public ActionResult DeleteEmailTemplate(int id)
    {
        detail_TTU_EmailTemplate_Data.DeleteEmailTemplate(id);

        return RedirectToAction("EmailTemplate");
    }
}

slTradeIn/Controllers/ContactsController.cs
using System.Net.Http.Headers;
using Google.Apis.Auth.OAuth2;
using Google.Apis.PeopleService.v1;
using Google.Apis.PeopleService.v1.Data;
using Google.Apis.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Graph;
using Microsoft.Graph.Models;
using slTradeIn.Data;
using slTradeIn.DataAccess;
using slTradeIn.Help;
using static Google.Apis.PeopleService.v1.PeopleResource.ConnectionsResource;
using Person = Google.Apis.PeopleService.v1.Data.Person;

namespace slTradeIn.Controllers;

public class ContactsController : CustomController
{
    private readonly Detail_TTU_userEmail_Data _ttuUserEmailData;

    public ContactsController(Detail_TTU_userEmail_Data ttuUserEmailData)
    {
        _ttuUserEmailData = ttuUserEmailData;
    }

    // GET: Contacts
    public async Task<ActionResult> Index(int page = 0)
    {
        ViewBag.Page = page;
        ViewBag.Count = _ttuUserEmailData.Count() / 10;
        return View(_ttuUserEmailData.List(page));
    }

    [HttpPost]
    public async Task<ActionResult> SaveGoogleContacts(ICollection<Person> people)
    {
        var emailList = new List<Detail_TTU_userEmail>();

        foreach (var person in people)
            if (person.EmailAddresses?.Count > 0)
                foreach (var emailAddress in person.EmailAddresses)
                    emailList.Add(new Detail_TTU_userEmail
                    {
                        vEmail = emailAddress.Value,
                        vName = person.Names[0].DisplayName,
                        vEmailGroup = "",
                        dCreatedDate = DateTime.Now,
                        bStatus = true,
                        iUserID = Convert.ToInt32(SessionTradeIn.iUserID),
                        vEmailProvider = "GOOGLE"
                    });

        _ttuUserEmailData.Save(emailList);
        return new OkResult();
    }

    [HttpPost]
    public async Task<ActionResult> SaveOutlookContacts(ICollection<Contact> people)
    {
        var emailList = new List<Detail_TTU_userEmail>();

        foreach (var person in people)
            if (person.EmailAddresses?.Count > 0)
                foreach (var emailAddress in person.EmailAddresses)
                    emailList.Add(new Detail_TTU_userEmail
                    {
                        vEmail = emailAddress.Address,
                        vName = person.DisplayName,
                        vEmailGroup = "",
                        dCreatedDate = DateTime.Now,
                        bStatus = true,
                        iUserID = Convert.ToInt32(SessionTradeIn.iUserID),
                        vEmailProvider = "OUTLOOK"
                    });

        _ttuUserEmailData.Save(emailList);
        return new OkResult();
    }

    [HttpPost]
    public async Task<ActionResult> GetGoogleContacts(string accessToken)
    {
        var credential = GoogleCredential.FromAccessToken(accessToken);

        var service = new PeopleServiceService(new BaseClientService.Initializer
        {
            HttpClientInitializer = credential,
            ApplicationName = "TechTradeUp"
        });

        var contactsList = await ListContactsGoogle(service);

        // List Contacts.
        return Json(contactsList.Connections);
    }

    [HttpPost]
    public async Task<ActionResult> GetOutlookContacts(string accessToken)
    {
        var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        var graphClient = new GraphServiceClient(httpClient);

        var contacts = await ListContacts(graphClient);

        return Json(contacts);
    }

    private async Task<List<Contact>> ListContacts(GraphServiceClient client)
    {
        try
        {
            var contacts = await client.Me.Contacts.GetAsync();

            return contacts.Value;
        }
        catch (Exception ex)
        {
            // Manejar errores
            throw ex;
        }
    }

    private Task<ListConnectionsResponse> ListContactsGoogle(PeopleServiceService service)
    {
        var listRequest = new ListRequest(service, "people/me")
        {
            PersonFields = "names,emailAddresses,organizations,phoneNumbers,locations"
        };

        return Task.Run(() => listRequest.ExecuteAsync());
    }

    private Task<ListConnectionsResponse> ListContactsOutlook(PeopleServiceService service)
    {
        var listRequest = new ListRequest(service, "people/me")
        {
            PersonFields = "names,emailAddresses,organizations,phoneNumbers,locations"
        };

        return Task.Run(() => listRequest.ExecuteAsync());
    }
}

slTradeIn/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace slTradeIn.Controllers;

public class LandingController : Controller
{
    public ActionResult Index()
    {
        return View();
    }

    public ActionResult EnvironmentalAdvocacy()
    {
        return View();
    }

    public ActionResult DataDestruction()
    {
        return View();
    }

    public ActionResult PeaceOfMind()
    {
        return View();
    }
}

slTradeIn/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using slTradeIn.DataAccess;
using slTradeIn.Help;

namespace slTradeIn.Controllers;

public class PartnerController : CustomController
{
    private readonly Detail_TTU_userEmail_Data _detail_TTU_UserEmail_Data;
    private readonly Detail_TTU_userEmailCampaign_Data _detail_TTU_UserEmailCampaign_Data;
    private readonly Detail_TTU_emailTemplate_Data detail_TTU_EmailTemplate_Data;

    public PartnerController(Detail_TTU_emailTemplate_Data detail_TTU_EmailTemplate_Data,
        Detail_TTU_userEmail_Data detail_TTU_UserEmail_Data,
        Detail_TTU_userEmailCampaign_Data detail_TTU_UserEmailCampaign_Data)
    {
        this.detail_TTU_EmailTemplate_Data = detail_TTU_EmailTemplate_Data;
        _detail_TTU_UserEmail_Data = detail_TTU_UserEmail_Data;
        _detail_TTU_UserEmailCampaign_Data = detail_TTU_UserEmailCampaign_Data;
    }

    // GET: Partner
    public ActionResult GenerateLinkCampaing()
    {
        ViewBag.EmailsRegistered = _detail_TTU_UserEmail_Data.Count();
        return View(_detail_TTU_UserEmailCampaign_Data.GetAll());
    }

    public ActionResult CampaignModal(int id)
    {
        return PartialView(_detail_TTU_UserEmailCampaign_Data.GetEmailGroups(id));
    }

    public ActionResult CreateEmailCampaign()
    {
        return View(_detail_TTU_UserEmailCampaign_Data.GetCreateView());
    }

    public ActionResult DuplicateEmailCampaign(int id)
    {
        return View("CreateEmailCampaign", _detail_TTU_UserEmailCampaign_Data.GetCreateViewWithID(id));
    }

    public string GetTemplateByID(int id)
    {
        return JsonConvert.SerializeObject(detail_TTU_EmailTemplate_Data.GetWithId(id));
    }

    //[HttpPost]
    //[ValidateInput(false)]
    //public ActionResult CreateEmailCampaign(FormCollection collection)
    //{
    //    if (ModelState.IsValid)
    //    {            
    //        CreateCampaignModel cet = new CreateCampaignModel();
    //        cet.iUserID = Convert.ToInt32(slTradeIn.Help.SessionTradeIn.iUserID);
    //        if(collection["iEmailTemplateID"] == null)
    //        {
    //            cet.iEmailTemplateID = Convert.ToInt32(collection["Templates"].ToString());
    //        }     
    //        else
    //        {
    //            cet.iEmailTemplateID = Convert.ToInt32(collection["iEmailTemplateID"].ToString());
    //        }
    //        cet.vSubject = collection["vSubject"].ToString();
    //        cet.vHTMLBody = collection["vHTMLBody"].ToString();
    //        cet.vName = collection["vName"].ToString();
    //        cet.EmailGroups = new List<EmailGroupModel>();
    //        foreach (var item in collection["SelectedEmailGroups"].Split(','))
    //        {
    //            cet.EmailGroups.Add(new EmailGroupModel { emailGroup = item.ToString() }); 
    //        }


    //        Detail_TTU_userEmailCampaign_Data ec = new Detail_TTU_userEmailCampaign_Data();
    //        ec.SaveEmailCampaign(cet);

    //        return RedirectToAction("GenerateLinkCampaing");
    //    }
    //    return View();
    //}
}

slTradeIn/Views/Shared/_Landing.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Landing Page</title>

    <meta name="keywords" content="WebSite Template"/>
    <meta name="description" content="TechTradeUp">
    <meta name="author" content="okler.net">

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Content/landing/img/favicon.ico" type="image/x-icon"/>
    <link rel="apple-touch-icon" href="~/Content/landing/img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Content/landing/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/animate/animate.compat.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/magnific-popup/magnific-popup.min.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/landing/css/theme.css">
    <link rel="stylesheet" href="~/Content/landing/css/theme-elements.css">
    <link rel="stylesheet" href="~/Content/landing/css/theme-blog.css">
    <link rel="stylesheet" href="~/Content/landing/css/theme-shop.css">

    <!-- Revolution Slider CSS -->
    <link rel="stylesheet" href="~/Content/landing/vendor/rs-plugin/css/settings.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/rs-plugin/css/layers.css">
    <link rel="stylesheet" href="~/Content/landing/vendor/rs-plugin/css/navigation.css">

    <!-- Demo CSS -->
    <link rel="stylesheet" href="~/Content/landing/css/demos/demo-digital-agency.css">

    <!-- Skin CSS -->
    <link id="skinCSS" rel="stylesheet" href="~/Content/landing/css/skins/skin-digital-agency.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Content/landing/css/custom.css">

    <!-- Head Libs -->
    <script src="~/Content/landing/vendor/modernizr/modernizr.min.js"></script>

    <style>
        html body .tabs.tabs-bottom .nav-tabs li .nav-link:hover, html.dark body .tabs.tabs-bottom .nav-tabs li .nav-link:hover, html body .tabs.tabs-bottom .nav-tabs .nav-link.active, html.dark body .tabs.tabs-bottom .nav-tabs .nav-link.active, html body .tabs.tabs-bottom .nav-tabs .nav-link.active:hover, html.dark body .tabs.tabs-bottom .nav-tabs .nav-link.active:hover, html body .tabs.tabs-bottom .nav-tabs .nav-link.active:focus, html.dark body .tabs.tabs-bottom .nav-tabs .nav-link.active:focus {
            border: none;
        }

        .tabs.tabs-simple .nav-tabs > li .nav-link, .tabs.tabs-simple .nav-tabs > li .nav-link:hover, .tabs.tabs-simple .nav-tabs > li .nav-link:focus {
            border: none;
        }

        .tabs.tabs-simple .nav-tabs > li {
            align-self: flex-start;
        }

        .service-item {
            background-color: #30C57A;
            padding-top: 2em;
        }

        .w-20 {
            width: 20%;
        }
    </style>
</head>
<body>

<header id="header" class="header-transparent header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': false, 'stickyChangeLogo': false, 'stickyStartAt': 30, 'stickyHeaderContainerHeight': 70}">
    <div class="header-body border-top-0 bg-dark box-shadow-none">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-logo">
                            <a asp-action="Index" asp-controller="Landing">
                                <img alt="Tech Trade Up" width="220" src="~/Content/landing/img/logo_white.png">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-end">
                    <div class="header-row">
                        <div class="header-nav header-nav-links header-nav-line header-nav-bottom-line header-nav-bottom-line-active-text-light header-nav-dropdowns-dark header-nav-light-text">
                            <div class="header-nav-main header-nav-main-text-capitalize header-nav-main-mobile-dark header-nav-main-square header-nav-main-dropdown-no-borders header-nav-main-effect-2 header-nav-main-sub-effect-1">
                                <nav class="collapse">
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li>
                                            <a class="nav-link active" href="#home">
                                                Home
                                            </a>
                                        </li>
                                        <li>
                                            <a class="nav-link" href="#howitworks">
                                                How it works
                                            </a>
                                        </li>
                                        <li>
                                            <a class="nav-link" href="#whoweare">
                                                Who are we?
                                            </a>
                                        </li>
                                        <li>
                                            <a class="nav-link" href="#footer">
                                                Contact
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <ul class="header-social-icons social-icons d-none d-sm-block social-icons-clean social-icons-icon-light social-icons-medium ms-5-5">
                            <li class="social-icons-linkedin">
                                <a href="https://www.linkedin.com/company/planitroi" target="_blank" title="Linkedin">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            </li>
                        </ul>
                        <button class="btn header-btn-collapse-nav ms-3 ms-sm-4" data-bs-toggle="collapse" data-bs-target=".header-nav-main nav">
                            <i class="fas fa-bars"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

@RenderBody()

</body>
</html>

slTradeIn/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using slTradeIn.Help
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en-US">
<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tech Trade-In</title>

    <meta name="keywords" content="WebSite Template"/>
    <meta name="description" content="Porto - Multipurpose Website Template">
    <meta name="author" content="okler.net">

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Porto/img/favicon.ico" type="image/x-icon"/>
    <link rel="apple-touch-icon" href="~/Porto/img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light&display=swap" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Porto/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/animate/animate.compat.css">
    <link rel="stylesheet" href="~/Porto/vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/magnific-popup/magnific-popup.min.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Porto/css/theme.css">
    <link rel="stylesheet" href="~/Porto/css/theme-elements.css">
    <link rel="stylesheet" href="~/Porto/css/theme-blog.css">
    <link rel="stylesheet" href="~/Porto/css/theme-shop.css">
    <!-- Skin CSS -->
    <link id="skinCSS" rel="stylesheet" href="~/Porto/css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Porto/css/custom.css">

    <!-- Head Libs -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/Porto/vendor/modernizr/modernizr.min.js"></script>
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea#vHTMLBody',
            height: 500,
            plugins: [
                'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
                'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
                'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | blocks | ' +
                'bold italic backcolor | alignleft aligncenter ' +
                'alignright alignjustify | bullist numlist outdent indent | ' +
                'removeformat | help',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:16px }'
        });
    </script>

    <!--DevExtreme-->
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Site.css" />

    <style>
        .btn.btn-primary, .btn.btn-primary:not(bg-transparent):hover {
            background-color: #74bd43;
            border: #74bd43;
        }

        #locationQuotes {
            padding: 0 20px;
        }

        [data-quotes="0"] #locationQuotes,
        [data-logistic="0"] .btn-danger,
        [data-quotes]:not([data-quotes="0"]) .btn-danger {
            display: none;
        }
    </style>

    @*
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    *@
</head>
<body data-plugin-page-transition>
<div class="body">
    <header id="header" class="header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': false, 'stickyEnableOnMobile': false, 'stickyStartAt': 70, 'stickyChangeLogo': false, 'stickyHeaderContainerHeight': 70}">
        <div class="header-body border-top-0 box-shadow-none">
            <div class="header-container header-container-md container">
                <div class="header-row">
                    <div class="header-column">
                        <div class="header-row">
                            <div class="header-logo">
                                <a href="@Url.Action("Index", "Landing")">
                                    <img alt="Porto" width="150" height="50" data-sticky-width="82" data-sticky-height="40" data-sticky-top="0" src="~/Porto/img/logo-default-slim.png">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="header-column justify-content-end">
                        <div class="header-row">
                            <div class="header-nav header-nav-line header-nav-bottom-line header-nav-bottom-line-no-transform header-nav-bottom-line-active-text-dark header-nav-bottom-line-effect-1 order-2 order-lg-1">
                                <div class="header-nav-main header-nav-main-square header-nav-main-dropdown-no-borders header-nav-main-effect-2 header-nav-main-sub-effect-1">
                                    <nav class="collapse">
                                        <ul class="nav nav-pills" id="mainNav">
                                            @if (User.IsInRole("ADMINISTRATOR"))
                                            {
                                                <li class="dropdown">
                                                    <a class="dropdown-item dropdown-toggle" href="@Url.Action("EmailTemplate", "Admin")">
                                                        Email Templates
                                                    </a>
                                                </li>
                                            }

                                            @if (User.IsInRole("TECH_PARTNER"))
                                            {
                                                <li class="dropdown">
                                                    <a class="dropdown-item dropdown-toggle" href="@Url.Action("Index", "Contacts")">
                                                        Contacts
                                                    </a>
                                                </li>
                                                <li class="dropdown">
                                                    <a class="dropdown-item dropdown-toggle" href="@Url.Action("GenerateLinkCampaing", "Partner")">
                                                        Generate Link Campaign
                                                    </a>
                                                </li>
                                            }
                                            <li class="dropdown">
                                                @if (!SignInManager.IsSignedIn(User))
                                                {
                                                    <a class="dropdown-item dropdown-toggle" asp-area="Identity" asp-page="/Account/Login">
                                                        Login
                                                    </a>
                                                }
                                                else
                                                {
                                                    <a class="dropdown-item dropdown-toggle" href="">
                                                        Hello @UserManager.GetUserName(User)!
                                                    </a>
                                                    <ul class="dropdown-menu">
                                                        <li class="dropdown-submenu dropdown-reverse">
                                                            <a class="dropdown-item dropdown-toggle" href="@Url.Action("BoxList", "Home")">Quotes</a>
                                                        </li>
                                                        <li class="dropdown-submenu dropdown-reverse">
                                                            <a class="dropdown-item dropdown-toggle" href="@Url.Action("Index", "ManualQuote")">Manual Quotes</a>
                                                        </li>
                                                        <li class="dropdown-submenu dropdown-reverse">
                                                            <a class="dropdown-item dropdown-toggle" href="@Url.Action("UserProfile", "Home")">Profile</a>
                                                        </li>
                                                        <li class="dropdown-submenu dropdown-reverse">
                                                            <a class="dropdown-item dropdown-toggle" href="@Url.Action("Index", "Location")">Locations</a>
                                                        </li>
                                                        <li class="dropdown-submenu dropdown-reverse">
                                                            <a class="dropdown-item dropdown-toggle" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Log out</a>
                                                        </li>
                                                    </ul>
                                                }
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <button class="btn header-btn-collapse-nav" data-bs-toggle="collapse" data-bs-target=".header-nav-main nav">
                                    <i class="fas fa-bars"></i>
                                </button>
                            </div>
                            <div class="header-nav-features header-nav-features-no-border header-nav-features-lg-show-border order-1 order-lg-2">
                                @if (!string.IsNullOrEmpty(SessionTradeIn.vUserEmail) && !string.IsNullOrEmpty(SessionTradeIn.iCartID) && Convert.ToInt32(SessionTradeIn.iCartID) > 0)
                                {
                                    <div class="header-nav-feature header-nav-features-cart d-inline-flex ms-2">
                                        <a href="@Url.Action("Box", "Home")" class="header-nav-feature">
                                            <img src="~/Porto/img/icons/icon-cart.svg" width="14" alt="" class="header-nav-top-icon-img">
                                            <span class="cart-info">
                                                <span class="cart-qty">1</span>
                                            </span>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()
</div>
@await RenderSectionAsync("scripts", false)
<!-- Vendor -->
<script src="~/Porto/vendor/plugins/js/plugins.min.js"></script>
<script src="~/Porto/vendor/gsap/gsap.min.js"></script>
<!-- Theme Base, Components and Settings -->
<script src="~/Porto/js/theme.js"></script>
<!-- Theme Custom -->
<script src="~/Porto/js/custom.js"></script>
<!-- Theme Initialization Files -->
<script src="~/Porto/js/theme.init.js"></script>
</body>
</html>