slTradeIn/Controllers/ManualQuoteController.cs
using Microsoft.AspNetCore.Mvc;
using slTradeIn.Data;
using slTradeIn.DataAccess;
using slTradeIn.Help;
using slTradeIn.Models;

namespace slTradeIn.Controllers;

public class ManualQuoteController : CustomController
{
    private readonly Detail_TTU_userCartDetail_Data _detail_TTU_UserCartDetail_Data;
    private readonly Detail_TTU_userManualQuote_Data _detail_TTU_UserManualQuote_Data;
    private readonly Detail_TTU_userManualQuoteDetail_Data _detail_TTU_UserManualQuoteDetail_Data;
    private readonly Detail_TTU_userManualQuoteLocation_Data _detail_TTU_UserManualQuoteLocation_Data;


    public ManualQuoteController(Detail_TTU_userManualQuote_Data detail_TTU_UserManualQuote_Data,
        Detail_TTU_userCartDetail_Data detail_TTU_UserCartDetail_Data,
        Detail_TTU_userManualQuoteDetail_Data detail_TTU_UserManualQuoteDetail_Data,
        Detail_TTU_userManualQuoteLocation_Data detail_TTU_UserManualQuoteLocation_Data)
    {
        _detail_TTU_UserManualQuote_Data = detail_TTU_UserManualQuote_Data;
        _detail_TTU_UserCartDetail_Data = detail_TTU_UserCartDetail_Data;
        _detail_TTU_UserManualQuoteDetail_Data = detail_TTU_UserManualQuoteDetail_Data;
        _detail_TTU_UserManualQuoteLocation_Data = detail_TTU_UserManualQuoteLocation_Data;
    }

    // GET: ManualQuote
    public ActionResult Index()
    {
        return View(_detail_TTU_UserManualQuote_Data.GetList(Convert.ToInt32(SessionTradeIn.iUserID)));
    }

    public ActionResult SelectManualQuote(int iManualQuoteID = 0)
    {
        SessionTradeIn.iManualQuoteID = iManualQuoteID.ToString();
        return RedirectToAction("Edit");
    }

    [HttpGet]
    public int QuoteCount()
    {
        var cartID = int.Parse(SessionTradeIn.iCartID);

        var count = _detail_TTU_UserCartDetail_Data.GetListCartDetail(cartID).Count;

        return count;
    }

    public ActionResult Edit()
    {
        var Q = _detail_TTU_UserManualQuote_Data.GetInfo(Convert.ToInt32(SessionTradeIn.iManualQuoteID));
        var Model = new ManualQuoteModel();
        if (Q == null)
            Model = new ManualQuoteModel
            {
                iUserID = Convert.ToInt32(SessionTradeIn.iUserID),
                bSerializedReport = Convert.ToBoolean(SessionTradeIn.bSerializedReport),
                vShippingType = Convert.ToInt32(SessionTradeIn.iShippingType),
                ListDetail =
                    new List<Detail_TTU_userManualQuoteDetail>(_detail_TTU_UserManualQuoteDetail_Data.GetList(0)),
                ListLocation = new List<ManualQuoteLocationModel>(
                    _detail_TTU_UserManualQuoteLocation_Data.GetList(0, Convert.ToInt32(SessionTradeIn.iUserID)))
            };
        else
            Model = new ManualQuoteModel
            {
                iUserID = Q.iUserID,
                bSerializedReport = Q.bSerializedReport,
                iBoxStatusID = Q.iBoxStatusID,
                iManualQuoteID = Q.iManualQuoteID,
                dSignDate = Q.dSignDate,
                vShippingType = Q.vShippingType,
                ListDetail =
                    new List<Detail_TTU_userManualQuoteDetail>(
                        _detail_TTU_UserManualQuoteDetail_Data.GetList(Q.iManualQuoteID)),
                ListLocation = new List<ManualQuoteLocationModel>(
                    _detail_TTU_UserManualQuoteLocation_Data.GetList(Q.iManualQuoteID,
                        Convert.ToInt32(SessionTradeIn.iUserID)))
            };

        return View(Model);
    }

    [HttpPost]
    public ActionResult Edit(ManualQuoteModel model)
    {
        var Q = _detail_TTU_UserManualQuote_Data.GetInfo(model.iManualQuoteID);
        if (Q == null)
        {
            model.iUserID = Convert.ToInt32(SessionTradeIn.iUserID);
            model.bSerializedReport = Convert.ToBoolean(SessionTradeIn.bSerializedReport);
            model.vShippingType = Convert.ToInt32(SessionTradeIn.iShippingType);


            model.iManualQuoteID = _detail_TTU_UserManualQuote_Data.SaveManualQuote(new Detail_TTU_userManualQuote
            {
                iUserID = Convert.ToInt32(SessionTradeIn.iUserID),
                bSerializedReport = model.bSerializedReport,
                vShippingType = model.vShippingType
            });
        }

        _detail_TTU_UserManualQuoteDetail_Data.SaveDetail(new Detail_TTU_userManualQuoteDetail
        {
            iManualQuoteID = model.iManualQuoteID,
            iQuantity = model.Quantity,
            vHDD = model.HDD,
            vManufacturer = model.Manufacturer,
            vModelNumber = model.ModelNumber,
            iManualQuoteDetID = model.iManualQuoteDetID,
            vProcessor = model.Processor,
            vRam = model.Ram
        });
        model.ListDetail = _detail_TTU_UserManualQuoteDetail_Data.GetList(model.iManualQuoteID);
        model.ListLocation = new List<ManualQuoteLocationModel>(
            _detail_TTU_UserManualQuoteLocation_Data.GetList(model.iManualQuoteID,
                Convert.ToInt32(SessionTradeIn.iUserID)));
        foreach (var item in model.ListLocation)
        {
            item.iManualQuoteID = model.iManualQuoteID;
            if (Request.Form.ContainsKey("chk_" + item.iLogisticID))
                item.bCheck = true;
            else
                item.bCheck = false;
        }

        _detail_TTU_UserManualQuoteLocation_Data.SaveLocation(model.ListLocation, model.iManualQuoteID);
        SessionTradeIn.iManualQuoteID = model.iManualQuoteID.ToString();

        return View(model);
    }

    public JsonResult SendManualQuote(int ID = 0)
    {
        var Data = _detail_TTU_UserManualQuoteDetail_Data.GetInfo(ID);


        return Json(Data);
    }

    public JsonResult GetInfoManualQuote(int ID = 0)
    {
        var Data = _detail_TTU_UserManualQuoteDetail_Data.GetInfo(ID);

        return Json(Data);
    }

    public JsonResult DeleteLocation(int iManualQuoteDetID = 0)
    {
        var Data = _detail_TTU_UserManualQuoteDetail_Data.DeleteDetail(iManualQuoteDetID);
        return Json(Data);
    }
}

slTradeIn/Views/ManualQuote/BeforeTradeIn.cshtml
@model slTradeIn.Models.BeforeTradeInModel
<script>
    function ShowEnviromentalModal() {
        $("#EnviromentalModal").modal("show");
    }
    function ShowLogisticModal() {
        $("#LogisticModal").modal("show");
    }
</script>
<style>
    .shipping-types {
        display: flex;
    }

    .shipping-types img {
        max-width: 100%;
    }

    .shipping-types > div {
        width: 33.33%;
        text-align: center;
        padding: 10px;
        border: 1px solid #aaa;
        margin: 0 5px;
    }
</style>
<div class="modal fade" id="EnviromentalModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="largeModalLabel">Sample Reports</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <img class="text-center" width="100%" src="~/Content/Images/Img/Enviromental.png" />
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="LogisticModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="largeModalLabel">
                    Which shipping method would you prefer?
                </h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body shipping-types">
                <div>
                    <img src="~/Content/Images/Shipping/Picture1.png" alt="" style="margin: 30px 0;">
                    <h4>I pack and ship</h4>
                    You pack all your devices and send it to our office.
                    <strong>
                        *If you do not have the packaging materials we can send them to you.
                    </strong>
                </div>
                <div>
                    <img src="~/Content/Images/Shipping/Picture2.png" alt="">
                    <h4>
                        I would pack and Tech Trade Up came to pick them
                    </h4>
                        Tech Trade Up provide you all the necessary materials for you to pack the devices,
                        and us will handle the pick-up.
                    <strong>*If you do not have the packaging materials we can send them to you.</strong>
                </div>
                <div>
                    <img src="~/Content/Images/Shipping/Picture3.png" alt="">
                    <h4>Pick, pack and ship</h4>
                    <p>
                        All the work will be taken care of by Tech Trade Up.
                        They will pick up, pack, and ship your devices for you.
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


    <div role="main" class="main">

        <section class="page-header page-header-modern bg-color-light-scale-1 page-header-lg">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 align-self-center p-static order-2 text-center">
                        <h1 class="font-weight-bold text-dark">Before we start the Trade-In</h1>
                    </div>
                    <div class="col-md-12 align-self-center order-1">
                        <ul class="breadcrumb d-block text-center">
                            <li><a href="@Url.Action("UserProfile","Home")">User Profile</a></li>
                            <li class="active">Trade-In</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <div class="container pt-3 pb-2">
            @Html.Partial("~/Views/ManualQuote/_ShippingForm.cshtml", Model)
        </div>
    </div>

slTradeIn/Views/ManualQuote/Edit.cshtml
@model slTradeIn.Models.ManualQuoteModel
@{
    ViewBag.Title = "Manual Quotes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    const fillFormMQ = location => {
        document.getElementById("Manufacturer").value = location.vManufacturer;
        document.getElementById("ModelNumber").value = location.vModelNumber;
        document.getElementById("HDD").value =  location.vHDD;
        document.getElementById("Ram").value = location.vRam;
        document.getElementById("Processor").value = location.vProcessor;
        document.getElementById("Quantity").value = location.iQuantity;
    };

    function ShowDetailModal(iManualQuoteDetID) {

        var checkboxes = document.querySelectorAll('input[type="checkbox"]');
        var checkedOne = Array.prototype.slice.call(checkboxes).some(x => x.checked);
        if (!checkedOne) {
            alert("You must select at least one location first");
            return;
        }
        $("#iManualQuoteDetID").val(iManualQuoteDetID);

        if (iManualQuoteDetID == "0")
        {
            fillFormMQ(new Proxy({}, { get: () => '' }));
        }
        else
        {
            var Data = { ID: iManualQuoteDetID };

            $.ajax({
                type: 'POST',
                data: JSON.stringify(Data),
                url: '@Url.Action("GetInfoManualQuote", "ManualQuote")',
                async: false,
                bDeferRender: true,
                bProcessing: true,
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    if (data == null) return;
                    fillFormMQ(data);
                },
            });
        }

        $("#DetailModal").modal("show");
    }

    function DeleteDetail() {
        var Data = {
            iManualQuoteDetID: $("#iManualQuoteDetID").val()
        };

        $.ajax({
            type: 'POST',
            data: JSON.stringify(Data),
            url: '@Url.Action("DeleteDetail", "ManualQuote")',
            async: false,
            bDeferRender: true,
            bProcessing: true,
            contentType: 'application/json; charset=utf-8',
            success: function () {
                window.location.href = "/ManualQuote/Edit";
            }
        });
    }

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>
<div role="main" class="main">

    <section class="page-header page-header-modern bg-color-light-scale-1 page-header-lg">
        <div class="container">
            <div class="row">
                <div class="col-md-12 align-self-center p-static order-2 text-center">
                    <h1 class="font-weight-bold text-dark">Manual Quote</h1>
                </div>
                <div class="col-md-12 align-self-center order-1">
                    <ul class="breadcrumb d-block text-center">
                        <li><a href="@Url.Action("UserProfile","Home")">User Profile</a></li>
                        <li class="active">Manual Quote</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


    <div class="container pt-3 pb-2">
        @using (Html.BeginForm("Edit", "ManualQuote", FormMethod.Post, new { @class = "needs-validation" }))
        {
            @Html.HiddenFor(q => q.iManualQuoteID, new { id = "iManualQuoteID" })
            @Html.HiddenFor(q => q.iManualQuoteDetID, new { id = "iManualQuoteDetID" })
            <div class="modal fade" id="DetailModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="largeModalLabel">Item</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true">×</button>
                        </div>

                        <div class="modal-body">
                            <div class="row">

                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2 required">Manufacturer (ex. Dell)</label>
                                <div class="col-lg-12">
                                    <input id="Manufacturer" class="form-control text-3 h-auto py-2" type="text" name="Manufacturer" value="" required>
                                </div>
                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2 required">Model Number (ex. Latitude 5480; for all apple products, the Part Number is required ex. MD101LL/A)</label>
                                <div class="col-lg-12">
                                    <input id="ModelNumber" class="form-control text-3 h-auto py-2" type="text" name="ModelNumber" value="" required>
                                </div>
                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2">HDD (ex. 256GB SSD)</label>
                                <div class="col-lg-12">
                                    <input id="HDD" class="form-control text-3 h-auto py-2" type="text" name="HDD" value="">
                                </div>
                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2">Ram (ex. 8GB (2x4GB))</label>
                                <div class="col-lg-12">
                                    <input id="Ram" class="form-control text-3 h-auto py-2" type="text" name="Ram" value="">
                                </div>
                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2">Processor (ex. Intel Core i5-6500)</label>
                                <div class="col-lg-12">
                                    <input id="Processor" class="form-control text-3 h-auto py-2" type="text" name="Processor" value="">
                                </div>
                                <label class="col-lg-12 col-form-label form-control-label line-height-9 pt-2 text-2 required">Quantity</label>
                                <div class="col-lg-12">
                                    <input id="Quantity" class="form-control text-3 h-auto py-2" type="text" name="Quantity" value="" onkeypress="return isNumber(event)" required>
                                </div>

                            </div>

                        </div>
                        <div class="modal-footer">
                            <input type="button" value="Delete" class="btn btn-danger" data-loading-text="Loading..." onclick="DeleteDetail();" id="btnDeleteLocation">
                            <input type="submit" value="Save" class="btn btn-primary" data-loading-text="Loading...">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col pb-3">
                            <h4 class="text-center">Trade In Location</h4>
                            <hr />
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>

                                        </th>
                                        <th>
                                            Location Label
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ListLocation)
                                    {
                                        <tr>
                                            <td>
                                                @if (item.bCheck)
                                                {
                                                    <input class="form-check-input" type="checkbox" value="@item.iLogisticID" name="chk_@item.iLogisticID" id="chk_@item.iLogisticID" checked>
                                                }
                                                else
                                                {
                                                    <input class="form-check-input" type="checkbox" value="@item.iLogisticID" name="chk_@item.iLogisticID" id="chk_@item.iLogisticID">
                                                }

                                            </td>
                                            <td>
                                                @String.Format("{0:MM/dd/yyyy}", item.vLocationLabel)
                                            </td>
                                            <td class="text-end">
                                                <button class="btn btn-default btn-sm rounded-0" onclick="location.href = '@Url.Action("Edit","ManualQuote",new { iCartID = item.iManualQuoteID})'" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-search"></i></button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-lg-9">

                </div>
                <div class="form-group col-lg-3">
                    <input type="button" value="Add new item" class="btn btn-primary float-end" data-loading-text="Loading..." onclick="ShowDetailModal(0);">
                </div>
            </div>


            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col pb-3">
                            <h4 class="text-center">Detail of assets</h4>
                            <hr />
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            Manufacturer
                                        </th>
                                        <th>
                                            Model Number
                                        </th>
                                        <th>
                                            HDD
                                        </th>
                                        <th>
                                            Ram
                                        </th>
                                        <th>
                                            Processor
                                        </th>
                                        <th>
                                            Quantity
                                        </th>
                                        <th class="text-end">

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.ListDetail)
                                    {
                                        <tr>
                                            <td>
                                                @item.vManufacturer
                                            </td>
                                            <td>
                                                @item.vModelNumber
                                            </td>
                                            <td>
                                                @item.vHDD
                                            </td>
                                            <td>
                                                @item.vRam
                                            </td>
                                            <td>
                                                @item.vProcessor
                                            </td>
                                            <td>
                                                @item.iQuantity
                                            </td>
                                            <td class="text-end">
                                                <button class="btn btn-default btn-sm rounded-0" onclick="ShowDetailModal(@item.iManualQuoteDetID)" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-search"></i></button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

                            
                            }
                        </div>
                    </div>

slTradeIn/Views/ManualQuote/Index.cshtml
@model List<slTradeIn.Data.vw_TTU_ManualQuoteList>


@{
    ViewBag.Title = "Manual Quotes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div role="main" class="main">

    <section class="page-header page-header-modern bg-color-light-scale-1 page-header-lg">
        <div class="container">
            <div class="row">
                <div class="col-md-12 align-self-center p-static order-2 text-center">
                    <h1 class="font-weight-bold text-dark">My Quotes</h1>
                </div>
                <div class="col-md-12 align-self-center order-1">
                    <ul class="breadcrumb d-block text-center">
                        <li><a href="@Url.Action("UserProfile","Home")">User Profile</a></li>
                        <li class="active">Manual Quotes</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <div class="container pt-3 pb-2">
        <input type="button" value="Create New Manual Quote" class="btn btn-primary btn-modern float-end" data-loading-text="Loading..." onclick="location.href='@Url.Action("SelectManualQuote","ManualQuote",new { iManualQuoteID = 0})'">

        <br />
        <br />
        <br />
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Date Created
                    </th>
                    <th>
                        Quote Status
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @String.Format("{0:MM/dd/yyyy}", item.dDateCreated)
                        </td>
                        <td>
                            @String.Format("{0:$ 0,0.##}", item.QuoteStatus)
                        </td>
                        <td class="text-center">
                            <button class="btn btn-default btn-sm rounded-0" onclick="location.href = '@Url.Action("SelectManualQuote","ManualQuote",new { iManualQuoteID = item.iManualQuoteID})'" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-search"></i></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>